spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:gsg
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss


#logging:
#  level:
#    root: DEBUG
#    org.apache.tomcat: DEBUG
#    org.apache.catalina: DEBUG

server:
  port: 8443
  ssl:
    key-store-password: password
    key-store: classpath:keystore.p12
    key-alias: gsg
  accesslog:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"






