swagger: "2.0"
info:
  title: "GetSetGift API"
  description: "This is api for getsetgift"
  version: "1.0.0"
basePath: "/v1"
tags: 
- name: "wishlist"
  description: "API to work with wishlist"
- name: "event"
  description: "API to work with events"
- name: "recommendation"
  description: "API to work with recommendations"
schemes:
- "http"
- "https"
paths:
  /wishlist/{wishlistId}:
    get:
      tags: 
      - "wishlist"
      summary: "Get wishlist by id"
      description: "Returns a single wishlist"
      produces:
      - "application/json"
      parameters:
      - name: "wishlistId"
        in: "path"
        description: "ID of wishlist to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Wishlist"
  /event/{eventId}:
    get:
      tags:
        - "event"
      summary: "Get event by id"
      description: "Returns a single event"
      produces:
        - "application/json"
      parameters:
        - name: "eventId"
          in: "path"
          description: "ID of the event to be returned"
          required: true
          type: "integer"
          format: "int64"
      responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/Event"
          
          
definitions:
  Wishlist:
    type: "object"
    properties:
      wishlistId:
        type: "integer"
        format: "int64"
        example: "22222"
      wishlistName: 
        type: "string"
        example: "Birthday Wishlist"
      wishlistNote:
        type: "string"
        example: "This is for my 40th birthday"
      gifts:
        type: "array"
        items:
          type: "string"
          
  Event:
    type: "object"
    properties:
      eventId: 
        type: "integer"
        format: "int64"
        example: "33333"
      eventHost: 
        type: "string"
        example: "dddd"
      eventDateTime:
        type: "string"
        format: "date-time"
        example: "11-27-2020:14-50-00"
      eventForPerson: 
        type: "string"
        example: "xyz abc"
      eventLocationAddress:
        type: "string"
        example: "123 park street ko"
      eventLocationMapLink:
        type: "string"
        example: "www.maps.google.com/kaldkjfak"

          
  EventWithWishlist:
    type: "object"
    properties:
      eventId: 
        type: "integer"
        format: "int64"
        example: "33333"
      eventHost: 
        type: "string"
        example: "dddd"
      eventDateTime:
        type: "string"
        format: "date-time"
        example: "11-27-2020:14-50-00"
      eventForPerson: 
        type: "string"
        example: "xyz abc"
      eventLocationAddress:
        type: "string"
        example: "123 park street ko"
      eventLocationMapLink:
        type: "string"
        example: "www.maps.google.com/kaldkjfak"
      eventWishlists:
        type: "array"
        items:
          $ref: "#/definitions/Wishlist"
          
        
      
        
      
        
      
      
          
        
      
      
      
     
      